In [106]:
from pandas import DataFrame

In [107]:
data1 = {'name' : ['김상순', '이순자', '강남길'], 
        'addr' : ['서울', '인천', '경기'],
        'age' : ['32','23','54']}
data1

{'name': ['김상순', '이순자', '강남길'],
 'addr': ['서울', '인천', '경기'],
 'age': ['32', '23', '54']}

In [108]:
df = DataFrame(data1)
df

  name addr age
0  김상순   서울  32
1  이순자   인천  23
2  강남길   경기  54

In [109]:
df2 = DataFrame(data1, columns=['name', 'age', 'addr'], index =['no1','no2','no3'])     # 순서, 인덱스 변경
df2

    name age addr
no1  김상순  32   서울
no2  이순자  23   인천
no3  강남길  54   경기

In [110]:
df2.columns

Index(['name', 'age', 'addr'], dtype='str')

In [111]:
df2.index

Index(['no1', 'no2', 'no3'], dtype='str')

In [112]:
df2['name']     # 특정 열만 가져오기

no1    김상순
no2    이순자
no3    강남길
Name: name, dtype: str

In [113]:
df2.name

no1    김상순
no2    이순자
no3    강남길
Name: name, dtype: str

In [114]:
df2.loc['no2']      # 특정 인덱스 행 가져오기
df2.iloc[2]     # 특정 행 번호로 가져오기

name    강남길
age      54
addr     경기
Name: no3, dtype: str

In [115]:
df2.loc[['no1', 'no3']]

    name age addr
no1  김상순  32   서울
no3  강남길  54   경기

In [116]:
df2.loc['no1':'no3']

    name age addr
no1  김상순  32   서울
no2  이순자  23   인천
no3  강남길  54   경기

In [117]:
df2.iloc[1]     # 행번호로 불러오기
df2.iloc[[0,2]]     # 행번호로 여러개 불러올 때는 [[]] 이중 사용

    name age addr
no1  김상순  32   서울
no3  강남길  54   경기

In [118]:
df2.iloc[0:2]

    name age addr
no1  김상순  32   서울
no2  이순자  23   인천

In [119]:
# 특정 데이터 추출
df2.name['no2']

'이순자'

In [120]:
df2['name']['no2']

'이순자'

In [121]:
# 특정 행테 특정 열 데이터 추출
df2.loc[['no1','no3'],['name', 'age']]

    name age
no1  김상순  32
no3  강남길  54

In [122]:
df2.iloc[[0,2],[0,1]]

    name age
no1  김상순  32
no3  강남길  54

In [123]:
df2.sort_index(ascending=False)     # 내림차순 정렬 (default는 오름차순)

    name age addr
no3  강남길  54   경기
no2  이순자  23   인천
no1  김상순  32   서울

In [124]:
df2.sort_values(by='age')      # 나이기준 오름차순
df2.sort_values(by='age', ascending=False)      # 나이기준 내림차순

    name age addr
no3  강남길  54   경기
no1  김상순  32   서울
no2  이순자  23   인천

In [125]:
df3 = DataFrame({'이원용': {'지역': '서울', 'age': 21},
        '박미자':{'지역':'경기','age':32},
        '최길동':{'지역':'부산','age':27},
        })
df3

    이원용 박미자 최길동
지역   서울  경기  부산
age  21  32  27

In [126]:
# 행<->열 변환
df3.T

     지역 age
이원용  서울  21
박미자  경기  32
최길동  부산  27

In [127]:
df2['gender']=['male','female','male']      # df3['gender'] -> 기존에 gender가 있으면 수정, 없으면 추가 기능
df2

    name age addr  gender
no1  김상순  32   서울    male
no2  이순자  23   인천  female
no3  강남길  54   경기    male

In [128]:
df2['age']=25       # 모든 age값 변경
df2

    name  age addr  gender
no1  김상순   25   서울    male
no2  이순자   25   인천  female
no3  강남길   25   경기    male

In [129]:
df2['addr']=['충청','경상','전라']
df2

    name  age addr  gender
no1  김상순   25   충청    male
no2  이순자   25   경상  female
no3  강남길   25   전라    male

In [130]:
# 특정 행, 특정 값 변경
df2.loc['no2','name']='더조은'
df2

    name  age addr  gender
no1  김상순   25   충청    male
no2  더조은   25   경상  female
no3  강남길   25   전라    male

In [131]:
# 행 추가
df2.loc['no4']=['최상길', 32,'제주', 'female']
df2

    name  age addr  gender
no1  김상순   25   충청    male
no2  더조은   25   경상  female
no3  강남길   25   전라    male
no4  최상길   32   제주  female

In [132]:
# 행 삭제
df4 = df2.drop(['no2'])
df4 = df2.drop(['no2', 'no3'])      # 여러 행 삭제
df4

    name  age addr  gender
no1  김상순   25   충청    male
no4  최상길   32   제주  female

In [133]:
df2

    name  age addr  gender
no1  김상순   25   충청    male
no2  더조은   25   경상  female
no3  강남길   25   전라    male
no4  최상길   32   제주  female

In [134]:
# 열 삭제
# del df2['gender']       # 원본이 바뀜
# df2

df5 = df2.drop(['gender'], axis=1)        # axis =1 -> 열
df5 = df2.drop(['gender', 'addr'], axis=1)        # 여러 열 삭제
df5

    name  age
no1  김상순   25
no2  더조은   25
no3  강남길   25
no4  최상길   32

In [135]:
df6 = DataFrame({'addr' : ['충청','제주','전라'],
                'tel' : ['042', '051','076'],
                'department' : ['컴퓨터공학', '통계학과', '디자인학과']
                })

df6

  addr  tel department
0   충청  042      컴퓨터공학
1   제주  051       통계학과
2   전라  076      디자인학과

In [136]:
import pandas as pd

In [ ]:
# on = 'addr' 이면 addr이 겹치는 것만 합치기
result = pd.merge(df2, df6, on = 'addr')
result

  name  age addr  gender  tel department
0  김상순   25   충청    male  042      컴퓨터공학
1  강남길   25   전라    male  076      디자인학과
2  최상길   32   제주  female  051       통계학과

In [141]:
result2 = pd.merge(df2, df6, how='left')        # df2를 기준으로 합쳐짐
result2

  name  age addr  gender  tel department
0  김상순   25   충청    male  042      컴퓨터공학
1  더조은   25   경상  female  NaN        NaN
2  강남길   25   전라    male  076      디자인학과
3  최상길   32   제주  female  051       통계학과

In [142]:
result3 = pd.merge(df2, df6, how='right')       # df6을 기준으로 합쳐짐
result3

  name  age addr  gender  tel department
0  김상순   25   충청    male  042      컴퓨터공학
1  최상길   32   제주  female  051       통계학과
2  강남길   25   전라    male  076      디자인학과

In [144]:
df7 = DataFrame({'addr' : ['충청','제주','경기'],
                'tel' : ['042', '051','076'],
                'department' : ['컴퓨터공학', '통계학과', '디자인학과']
                })

In [ ]:
result4 = pd.merge(df2, df7, how='outer')       # 한쪽 데이터프레임에만 있는 값도 합쳐짐
result4

  name   age addr  gender  tel department
0  NaN   NaN   경기     NaN  076      디자인학과
1  더조은  25.0   경상  female  NaN        NaN
2  강남길  25.0   전라    male  NaN        NaN
3  최상길  32.0   제주  female  051       통계학과
4  김상순  25.0   충청    male  042      컴퓨터공학

In [146]:
# 데이터 프레임 연결
result5 = pd.concat([df2,df7])
result5

    name   age addr  gender  tel department
no1  김상순  25.0   충청    male  NaN        NaN
no2  더조은  25.0   경상  female  NaN        NaN
no3  강남길  25.0   전라    male  NaN        NaN
no4  최상길  32.0   제주  female  NaN        NaN
0    NaN   NaN   충청     NaN  042      컴퓨터공학
1    NaN   NaN   제주     NaN  051       통계학과
2    NaN   NaN   경기     NaN  076      디자인학과