In [1]:
from pandas import DataFrame

In [2]:
data1 = {'name' : ['김상순', '이순자', '강남길'], 
        'addr' : ['서울', '인천', '경기'],
        'age' : ['32','23','54']}
data1

{'name': ['김상순', '이순자', '강남길'],
 'addr': ['서울', '인천', '경기'],
 'age': ['32', '23', '54']}

In [3]:
df = DataFrame(data1)
df

  name addr age
0  김상순   서울  32
1  이순자   인천  23
2  강남길   경기  54

In [ ]:
df2 = DataFrame(data1, columns=['name', 'age', 'addf'], index =['no1','no2','no3'])     # 순서, 인덱스 변경
df2

    name age addf
no1  김상순  32  NaN
no2  이순자  23  NaN
no3  강남길  54  NaN

In [6]:
df2.columns

Index(['name', 'age', 'addf'], dtype='str')

In [7]:
df2.index

Index(['no1', 'no2', 'no3'], dtype='str')

In [ ]:
df2['name']     # 특정 열만 가져오기

no1    김상순
no2    이순자
no3    강남길
Name: name, dtype: str

In [9]:
df2.name

no1    김상순
no2    이순자
no3    강남길
Name: name, dtype: str

In [ ]:
df2.loc['no2']      # 특정 인덱스 행 가져오기
df2.iloc[2]     # 특정 행 번호로 가져오기

name    강남길
age      54
addf    NaN
Name: no3, dtype: object

In [ ]:
df2.loc[[]]