In [2]:
import pandas as pd

In [3]:
data1 = {
    '시도': ['서울', '경기', '인천', '부산', '대전'],
    '구분': ['특별시', '도', '광역시','광역시','광역시'],
    '인구': ['990만명','1300만명','350만명','300만명','150만명'],
    '면적': [600.5, '10,171','1,029', 747.5, 564.6]
}

df = pd.DataFrame(data1)
df

   시도   구분      인구      면적
0  서울  특별시   990만명   600.5
1  경기    도  1300만명  10,171
2  인천  광역시   350만명   1,029
3  부산  광역시   300만명   747.5
4  대전  광역시   150만명   564.6

In [4]:
# csv 파일로 저장
df.to_csv('output/mydata1.csv')

In [5]:
# csv 파일 불러오기
df1 = pd.read_csv('output/mydata1.csv')
df1

   Unnamed: 0  시도   구분      인구      면적
0           0  서울  특별시   990만명   600.5
1           1  경기    도  1300만명  10,171
2           2  인천  광역시   350만명   1,029
3           3  부산  광역시   300만명   747.5
4           4  대전  광역시   150만명   564.6

In [6]:
# 컬럼명 지정
df2 = pd.read_csv('output/mydata1.csv', names = ['no','구분','면적','시도','인구'])
df2

    no  구분   면적      시도      인구
0  NaN  시도   구분      인구      면적
1  0.0  서울  특별시   990만명   600.5
2  1.0  경기    도  1300만명  10,171
3  2.0  인천  광역시   350만명   1,029
4  3.0  부산  광역시   300만명   747.5
5  4.0  대전  광역시   150만명   564.6

In [7]:
pd.read_csv('output/mydata1.csv', index_col = 'no', names=['no','구분','면적','시도','인구'])

     구분   면적      시도      인구
no
NaN  시도   구분      인구      면적
0.0  서울  특별시   990만명   600.5
1.0  경기    도  1300만명  10,171
2.0  인천  광역시   350만명   1,029
3.0  부산  광역시   300만명   747.5
4.0  대전  광역시   150만명   564.6

In [8]:
df3 = pd.read_csv('output/mydata1.csv', index_col = 'no', names=['no','구분','면적','시도','인구'], skiprows=[0,2,3])
df3

    구분   면적     시도     인구
no
0   서울  특별시  990만명  600.5
3   부산  광역시  300만명  747.5
4   대전  광역시  150만명  564.6

In [10]:
df4 = pd.read_csv('output/mydata1.csv', index_col = 'no', names=['no','구분','면적','시도','인구'], skiprows=[0], nrows=3)
df4

    구분   면적      시도      인구
no
0   서울  특별시   990만명   600.5
1   경기    도  1300만명  10,171
2   인천  광역시   350만명   1,029

In [12]:
df5 = pd.read_csv('data/satisfaction.txt')
df5

  매우만족   만족    불만
0    5    3     1
1   호감   보통   비호감