In [1]:
import pandas as pd

# 결측치 데이터
df_missing = pd.DataFrame({
    '이름': ['민수', '지영', '서준', '하은'],
    '부서': ['개발팀', '인사팀', None, '개발팀'],
    '점수': [90, None, 85, None]
})

# 부서 필터링 데이터
df = pd.DataFrame({
    '이름': ['민수', '지영', '서준', '하은', '도윤'],
    'department': ['개발팀', '인사팀', '개발팀', '영업팀', '개발팀'],
    '나이': [25, 29, 31, 27, 24]
})

#### 문제 1. 결측치 개수 확인하기

df_missing 에서 각 열에 결측치가 몇 개씩 있는지 확인

In [2]:
df_missing.isnull().sum()

이름    0
부서    1
점수    2
dtype: int64

#### 문제 2. 결측치가 있는 행 삭제하기

df_missing에서 결측치가 하나라도 포함된 행을 삭제하고 결과를 출력

In [3]:
df_missing.dropna()

   이름   부서    점수
0  민수  개발팀  90.0

#### 문제 3. 결측치를 0으로 채우기

df_missing의 모든 결측치를 숫자 '0'으로 채운 결과를 출력

In [4]:
df_missing.fillna(0)

   이름   부서    점수
0  민수  개발팀  90.0
1  지영  인사팀   0.0
2  서준    0  85.0
3  하은  개발팀   0.0

#### 문제 4. JSON 파일 불러오기

pr_employees.json 파일을 판다스로 불러와 DataFrame으로 출력

In [5]:
import json

df = pd.read_json('data/pr_employees.json')
df1 = pd.DataFrame(df)
df1

   이름 department  경력
0  민수        개발팀   2
1  지영        인사팀   5
2  서준        개발팀   1

#### 문제 5. 조건에 맞는 행 필터링하기

문제 4의 변수에서 department가 '개발팀'인 행만 추출

In [6]:
df[df['department']=='개발팀']

   이름 department  경력
0  민수        개발팀   2
2  서준        개발팀   1

#### 문제 6. 엑셀 파일 불러오기

pr_transport.xlsx를 불러와 df_excel에 저장한 뒤, 처음 5개 행을 확인

In [7]:
df_excel =pd.read_excel('data/pr_transport.xlsx')
df_excel[:5]

    선별   차종  총이용인원    요금
0  경부선  승용차   1200  3000
1  경부선   버스    850  5000
2  호남선  승용차   1500  2500
3  경부선  화물차   1800  4000
4  호남선   버스    700  4500

#### 문제 7. 그룹별 데이터 가져오기

문제 6에서 불러와서 저장한 변수의 값들을 선별,
열 기준으로 그룹화한 다음, '경부선' 그룹만 df_group1 변수에 저장하고 출력

In [8]:
df_group1 = df_excel.groupby('선별').count()
df_group1=df_excel[df_excel['선별'] == '경부선']
df_group1

    선별   차종  총이용인원    요금
0  경부선  승용차   1200  3000
1  경부선   버스    850  5000
3  경부선  화물차   1800  4000

#### 문제 8. 조건 두 개를 동시에 만족하는 행 찾기

문제 6에서 불러와서 저장한 변수의 값들을 선별이 '경부선'이고 총이용인원이 1000 이상인 행만 추출

In [9]:
df_result=df_excel[(df_excel.선별=='경부선')&(df_excel.총이용인원 >= 1000)]
df_result

    선별   차종  총이용인원    요금
0  경부선  승용차   1200  3000
3  경부선  화물차   1800  4000

#### 문제 9. 그룹별 개수·평균·합계 구하기

문제 6에서 불러와서 저장한 변수의 값들을 선별별로 그룹화해 다음을 각각 구하기

1. 각 그룹의 열별 데이터 개수
2. 각 그룹의 숫자 열 평균
3. 각 그룹의 숫자 열 합계
4. 앞 문제에서 가져온 df_group1의 차종 데이터 개수

In [12]:
print(df_excel.groupby('선별').count())
print(df_excel.mean(numeric_only=True))
print(df_excel.sum())
print(df_excel['차종'].count())

     차종  총이용인원  요금
선별
경부선   3      3   3
호남선   3      3   3
총이용인원    1191.666667
요금       3750.000000
dtype: float64
선별       경부선경부선호남선경부선호남선호남선
차종         승용차버스승용차화물차버스화물차
총이용인원                  7150
요금                    22500
dtype: object
6

#### 문제 10. 정규표현식으로 숫자 찾기

다음 문자열에서 연속된 숫자 부분만 모두 찾아 리스트로 출력

In [ ]:
import re

text = '주문번호 A102, 상품 35개, 추가 주문 240개'

result = re.findall('\d+', text)
result

<>:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\mega\AppData\Local\Temp\ipykernel_15100\3746664865.py:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  result = re.findall('\d+', text)

['102', '35', '240']